name: Run Regression Suite

on:
  workflow_dispatch:

jobs:
  regression-suite:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Move regression.xml to resources
        run: mkdir -p src/test/resources && mv regression.xml src/test/resources/

      - name: Build with Maven
        run: mvn clean test "-Dtestng.suiteXmlFiles=src/test/resources/regression.xml"
