name: Regression Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Run tests
        run: ./gradlew test

      - name: Upload test results
        uses: actions/uploadThe job is failing because it uses a deprecated version-artifact@v4
        with:
          name: test-results of `actions/upload-artifact: v3`. To resolve this
          path: build/test-results
